---
# destroy instance
- name: User confirm
  pause:
    prompt: Please confirm you want to destroy "{{ resource.name }}" in "{{ gcp_project }}" Press return to continue. Press Ctrl+c and then "a" to abort

- name: destroying GCP instance
  gcp_compute_instance:
    state: absent
    name: "{{ resource.name }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
