---
- name: create disks
  gcp_compute_disk:
    name: "{{ name }}"
    size_gb: "{{ disk_size }}"
    type: "{{ disk_type }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- name: attach disk to GCP instance
  command:
    gcloud compute instances attach-disk "{{ instance_to_attach }}" --disk "{{ name }}" --zone "{{ zone }}"
