---
- name: detach disk from GCP instance
  command:
    gcloud compute instances detach-disk "{{ instance_attached }}" --disk "{{ name }}" --zone "{{ zone }}"

- name: destroy disks
  gcp_compute_disk:
    name: "{{ name }}"
    zone: "{{ zone }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
